<a href="https://colab.research.google.com/github/Xavier-ML/-Fundamentos-de-Redes-Neuronales-con-Python-y-Keras/blob/main/Dimensiones%2C_tensores_y_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Scalar

In [2]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

## Vector

In [4]:
x = np.array([42,23,453,21,32,1,3,7])
print(x.shape)
x.ndim

(8,)


1

## Matrix

In [5]:
x = np.array([[42,23,453],
             [34,343,24]])
print(x.shape)
x.ndim

(2, 3)


2

## Tensor

In [6]:
x = np.array([[[42,23,453],
             [34,343,24]],
             [[42,23,453],
             [34,343,24]],
             [[42,23,453],
             [34,343,24]],
             [[42,23,453],
             [34,343,24]]])
print(x.shape)
x.ndim

(4, 2, 3)


3

## Reshape

In [7]:
x = np.array([[0,1],
             [2,3],
             [4,5],
             [6,7]])
x.shape

(4, 2)

In [8]:
x.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [9]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [11]:
x.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])